#define RETRO_TAPPING

#define COMBO_TERM 25

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "bmOlV/ga9XKw"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 9

#define RGB_MATRIX_STARTUP_SPD 60
